In [1]:
import numpy as np
from numpy import genfromtxt

In [2]:
data = genfromtxt("DATA/bank_note_data.txt", delimiter=",")
data


array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699,   0.     ],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ,   0.     ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645,   0.     ],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ,   1.     ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ,   1.     ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ,   1.     ]])

In [3]:
labels = data[:,4]
labels

array([0., 0., 0., ..., 1., 1., 1.])

In [5]:
features = data[:,0:4]
features

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ]])

In [6]:
X = features
y = labels

In [7]:
from sklearn.model_selection import train_test_split

In [8]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [11]:
len(X_train)

919

In [12]:
len(X)

1372

In [13]:
len(X_test)

453

In [15]:
from sklearn.preprocessing import MinMaxScaler

In [16]:
scaler_object = MinMaxScaler()

In [17]:
scaler_object.fit(X_train)

MinMaxScaler(copy=True, feature_range=(0, 1))

In [19]:
scaled_X_train = scaler_object.transform(X_train)

In [20]:
scaled_X_test = scaler_object.transform(X_test)

In [21]:
scaled_X_train.max()

1.0000000000000002

In [22]:
X_train

array([[-0.8734  , -0.033118, -0.20165 ,  0.55774 ],
       [ 2.0177  ,  1.7982  , -2.9581  ,  0.2099  ],
       [-0.36038 ,  4.1158  ,  3.1143  , -0.37199 ],
       ...,
       [-7.0364  ,  9.2931  ,  0.16594 , -4.5396  ],
       [-3.4605  ,  2.6901  ,  0.16165 , -1.0224  ],
       [-3.3582  , -7.2404  , 11.4419  , -0.57113 ]])

In [23]:
scaled_X_train

array([[4.44850688e-01, 5.14130449e-01, 2.18194638e-01, 8.50172258e-01],
       [6.53339968e-01, 5.82655745e-01, 9.93242398e-02, 8.17696322e-01],
       [4.81846700e-01, 6.69377018e-01, 3.61193167e-01, 7.63368407e-01],
       ...,
       [4.11050776e-04, 8.63104170e-01, 2.34046756e-01, 3.74261253e-01],
       [2.58284115e-01, 6.16029366e-01, 2.33861752e-01, 7.02643151e-01],
       [2.65661395e-01, 2.44444278e-01, 7.20316361e-01, 7.44775785e-01]])

In [25]:
from keras.models import Sequential
from keras.layers import Dense

In [28]:
model = Sequential()

model.add( Dense( 4 , input_dim=4 , activation="relu")   )

model.add(Dense(8,activation = "relu"))

model.add( Dense(1,activation="sigmoid") )

In [29]:
model.compile(loss="binary_crossentropy",optimizer="adam",metrics=["accuracy"])

In [43]:
model.fit(scaled_X_train,y_train,epochs=100,verbose=2)

Epoch 1/100
 - 0s - loss: 0.2335 - acc: 0.9815
Epoch 2/100
 - 0s - loss: 0.2281 - acc: 0.9793
Epoch 3/100
 - 0s - loss: 0.2220 - acc: 0.9848
Epoch 4/100
 - 0s - loss: 0.2174 - acc: 0.9815
Epoch 5/100
 - 0s - loss: 0.2115 - acc: 0.9848
Epoch 6/100
 - 0s - loss: 0.2069 - acc: 0.9859
Epoch 7/100
 - 0s - loss: 0.2020 - acc: 0.9848
Epoch 8/100
 - 0s - loss: 0.1970 - acc: 0.9859
Epoch 9/100
 - 0s - loss: 0.1940 - acc: 0.9859
Epoch 10/100
 - 0s - loss: 0.1899 - acc: 0.9891
Epoch 11/100
 - 0s - loss: 0.1847 - acc: 0.9880
Epoch 12/100
 - 0s - loss: 0.1806 - acc: 0.9902
Epoch 13/100
 - 0s - loss: 0.1769 - acc: 0.9924
Epoch 14/100
 - 0s - loss: 0.1732 - acc: 0.9924
Epoch 15/100
 - 0s - loss: 0.1695 - acc: 0.9902
Epoch 16/100
 - 0s - loss: 0.1662 - acc: 0.9924
Epoch 17/100
 - 0s - loss: 0.1625 - acc: 0.9902
Epoch 18/100
 - 0s - loss: 0.1590 - acc: 0.9935
Epoch 19/100
 - 0s - loss: 0.1565 - acc: 0.9924
Epoch 20/100
 - 0s - loss: 0.1531 - acc: 0.9946
Epoch 21/100
 - 0s - loss: 0.1504 - acc: 0.9913
E

In [32]:
#model.predict_classes(scaled_X_test)

In [44]:
model.metrics_names

['loss', 'acc']

In [45]:
from sklearn.metrics import confusion_matrix, classification_report

In [46]:
prediction = model.predict_classes(scaled_X_test)

In [47]:
confusion_matrix(y_test , prediction)

array([[256,   1],
       [  0, 196]], dtype=int64)

In [48]:
print(classification_report(y_test,prediction))

             precision    recall  f1-score   support

        0.0       1.00      1.00      1.00       257
        1.0       0.99      1.00      1.00       196

avg / total       1.00      1.00      1.00       453



In [49]:
model.save("DATA/mysupermodel.h5")

In [50]:
from keras.models import load_model
newmodel = load_model("DATA/mysupermodel.h5")

In [51]:
newmodel.predict_classes(scaled_X_test)

array([[0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
    